# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyProto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyProto
  pod 'SwiftProtobuf', '~> 1.18.0'

  target 'StudyProtoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyProtoUITests' do
    # Pods for testing
  end

end
